
#line 3 "lex.EPSIO_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define EPSIO_yyconst const
#else
#define EPSIO_yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (EPSIO_yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((EPSIO_yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE EPSIO_yyrestart(EPSIO_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default EPSIO_input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct EPSIO_yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int EPSIO_yyleng;

extern FILE *EPSIO_yyin, *EPSIO_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the EPSIO_input stream. */
#define EPSIO_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up EPSIO_yytext. */ \
        int EPSIO_yyless_macro_arg = (n); \
        YY_LESS_LINENO(EPSIO_yyless_macro_arg);\
		*EPSIO_yy_cp = (EPSIO_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(EPSIO_yy_c_buf_p) = EPSIO_yy_cp = EPSIO_yy_bp + EPSIO_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up EPSIO_yytext again */ \
		} \
	while ( 0 )

#define EPSIO_unput(c) EPSIO_yyEPSIO_unput( c, (EPSIO_yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int EPSIO_yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct EPSIO_yy_buffer_state
	{
	FILE *EPSIO_yy_EPSIO_input_file;

	char *EPSIO_yy_ch_buf;		/* EPSIO_input buffer */
	char *EPSIO_yy_buf_pos;		/* current position in EPSIO_input buffer */

	/* Size of EPSIO_input buffer in bytes, not including room for EOB
	 * characters.
	 */
	EPSIO_yy_size_t EPSIO_yy_buf_size;

	/* Number of characters read into EPSIO_yy_ch_buf, not including EOB
	 * characters.
	 */
	int EPSIO_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int EPSIO_yy_is_our_buffer;

	/* Whether this is an "interactive" EPSIO_input source; if so, and
	 * if we're using stdio for EPSIO_input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching EPSIO_input after
	 * each newline.
	 */
	int EPSIO_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int EPSIO_yy_at_bol;

    int EPSIO_yy_bs_lineno; /**< The line count. */
    int EPSIO_yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the EPSIO_input buffer when we reach the
	 * end of it.
	 */
	int EPSIO_yy_fill_buffer;

	int EPSIO_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the EPSIO_input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via EPSIO_yyrestart()), so that the user can continue scanning by
	 * just pointing EPSIO_yyin at a new EPSIO_input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of EPSIO_input buffers. */
static size_t EPSIO_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t EPSIO_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * EPSIO_yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (EPSIO_yy_buffer_stack) \
                          ? (EPSIO_yy_buffer_stack)[(EPSIO_yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (EPSIO_yy_buffer_stack)[(EPSIO_yy_buffer_stack_top)]

/* EPSIO_yy_hold_char holds the character lost when EPSIO_yytext is formed. */
static char EPSIO_yy_hold_char;
static int EPSIO_yy_n_chars;		/* number of characters read into EPSIO_yy_ch_buf */
int EPSIO_yyleng;

/* Points to current character in buffer. */
static char *EPSIO_yy_c_buf_p = (char *) 0;
static int EPSIO_yy_init = 1;		/* whether we need to initialize */
static int EPSIO_yy_start = 0;	/* start state number */

/* Flag which is used to allow EPSIO_yywrap()'s to do buffer switches
 * instead of setting up a fresh EPSIO_yyin.  A bit of a hack ...
 */
static int EPSIO_yy_did_buffer_switch_on_eof;

void EPSIO_yyrestart (FILE *EPSIO_input_file  );
void EPSIO_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE EPSIO_yy_create_buffer (FILE *file,int size  );
void EPSIO_yy_delete_buffer (YY_BUFFER_STATE b  );
void EPSIO_yy_flush_buffer (YY_BUFFER_STATE b  );
void EPSIO_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void EPSIO_yypop_buffer_state (void );

static void EPSIO_yyensure_buffer_stack (void );
static void EPSIO_yy_load_buffer_state (void );
static void EPSIO_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER EPSIO_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE EPSIO_yy_scan_buffer (char *base,EPSIO_yy_size_t size  );
YY_BUFFER_STATE EPSIO_yy_scan_string (EPSIO_yyconst char *EPSIO_yy_str  );
YY_BUFFER_STATE EPSIO_yy_scan_bytes (EPSIO_yyconst char *bytes,int len  );

void *EPSIO_yyalloc (EPSIO_yy_size_t  );
void *EPSIO_yyrealloc (void *,EPSIO_yy_size_t  );
void EPSIO_yyfree (void *  );

#define EPSIO_yy_new_buffer EPSIO_yy_create_buffer

#define EPSIO_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        EPSIO_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            EPSIO_yy_create_buffer(EPSIO_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_is_interactive = is_interactive; \
	}

#define EPSIO_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        EPSIO_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            EPSIO_yy_create_buffer(EPSIO_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *EPSIO_yyin = (FILE *) 0, *EPSIO_yyout = (FILE *) 0;

typedef int EPSIO_yy_state_type;

extern int EPSIO_yylineno;

int EPSIO_yylineno = 1;

extern char *EPSIO_yytext;
#define EPSIO_yytext_ptr EPSIO_yytext

static EPSIO_yy_state_type EPSIO_yy_get_previous_state (void );
static EPSIO_yy_state_type EPSIO_yy_try_NUL_trans (EPSIO_yy_state_type current_state  );
static int EPSIO_yy_get_next_buffer (void );
static void EPSIO_yy_fatal_error (EPSIO_yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up EPSIO_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(EPSIO_yytext_ptr) = EPSIO_yy_bp; \
	EPSIO_yyleng = (size_t) (EPSIO_yy_cp - EPSIO_yy_bp); \
	(EPSIO_yy_hold_char) = *EPSIO_yy_cp; \
	*EPSIO_yy_cp = '\0'; \
	(EPSIO_yy_c_buf_p) = EPSIO_yy_cp;

#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct EPSIO_yy_trans_info
	{
	flex_int32_t EPSIO_yy_verify;
	flex_int32_t EPSIO_yy_nxt;
	};
static EPSIO_yyconst flex_int16_t EPSIO_yy_accept[34] =
    {   0,
        0,    0,   18,   16,   13,   14,   16,   16,    6,    7,
       16,    8,   12,   16,    1,   11,    3,    9,   10,    2,
        0,    5,    0,    0,    0,    4,    1,   15,    3,    5,
        0,    0,    0
    } ;

static EPSIO_yyconst flex_int32_t EPSIO_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,    9,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    1,    1,
       14,    1,    1,    1,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       16,   17,   18,    1,   15,    1,   15,   15,   15,   15,

       19,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,    1,   20,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static EPSIO_yyconst flex_int32_t EPSIO_yy_meta[21] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    2,    1,    3,    1,    2,    1
    } ;

static EPSIO_yyconst flex_int16_t EPSIO_yy_base[37] =
    {   0,
        0,    0,   48,   55,   55,   55,   17,   42,   55,   55,
       19,   55,   55,   23,   17,   55,    0,   55,   55,    0,
       18,   55,   19,   23,   21,   55,   12,   55,    0,   24,
       25,   29,   55,   49,   52,   22
    } ;

static EPSIO_yyconst flex_int16_t EPSIO_yy_def[37] =
    {   0,
       33,    1,   33,   33,   33,   33,   34,   35,   33,   33,
       33,   33,   33,   33,   33,   33,   36,   33,   33,   36,
       34,   33,   34,   34,   35,   33,   33,   33,   36,   34,
       34,   34,    0,   33,   33,   33
    } ;

static EPSIO_yyconst flex_int16_t EPSIO_yy_nxt[76] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,   11,   12,
       13,   14,   15,   16,   17,   18,    4,   19,   20,    4,
       22,   22,   30,   29,   27,   26,   22,   22,   30,   27,
       28,   27,   30,   23,   23,   23,   24,   24,   24,   31,
       23,   32,   24,   24,   24,   23,   26,   33,   24,   21,
       21,   21,   25,   25,    3,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33
    } ;

static EPSIO_yyconst flex_int16_t EPSIO_yy_chk[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        7,   21,   23,   36,   27,   25,   24,   30,   31,   15,
       14,   11,   32,    7,   21,   23,    7,   21,   23,   24,
       30,   31,   24,   30,   31,   32,    8,    3,   32,   34,
       34,   34,   35,   35,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33
    } ;

static EPSIO_yy_state_type EPSIO_yy_last_accepting_state;
static char *EPSIO_yy_last_accepting_cpos;

extern int EPSIO_yy_flex_debug;
int EPSIO_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define EPSIO_yymore() EPSIO_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *EPSIO_yytext;
#line 1 "./lexer.l"
#line 9 "./lexer.l"
/*
 * File:         lexer.l
 * Description:  Lexical analyser for PROLOGIO; can be used with
 *               either lex and flex.
 */
#include <string.h>
#if !defined(__SC__) && !defined(__DMC__) && !defined(_Win32)
#include <unistd.h>
#endif

/* +++steve162e: added, otherwise, EPSIO_EPSIO_input will be undefined (at least under LINUX)
             please check, if this is also TRUE under other UNIXes.
 */

#if defined(FLEX_SCANNER) && defined(_LINUX)
#define EPSIO_EPSIO_input my_EPSIO_input
#endif
/* ---steve162e */

/* #include "wxexio.h" */

#define Return(x) return x;

#if defined(VMS) && !defined(strdup)
#define strdup(s) (strcpy((char *)malloc(strlen(s)+1), s));
#endif

static size_t lex_buffer_length = 0;
static const char *lex_buffer = NULL;
static size_t lex_string_ptr = 0;
static int lex_read_from_string = 0;

static int my_EPSIO_input(void);

#ifdef FLEX_SCANNER
# undef YY_INPUT
# define YY_INPUT(buf,result,max_size) \
   if (lex_read_from_string) \
   {  int c = my_EPSIO_input(); result = (c == 0) ? YY_NULL : ((buf)[0]=(c), 1); } \
   else \
	if ( (result = read( fileno(EPSIO_yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#else
# undef EPSIO_unput
# define EPSIO_unput(_c) my_EPSIO_unput(_c)
  static int my_EPSIO_unput(char);
#endif

#line 512 "lex.EPSIO_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#if !defined(__SC__) && !defined(__DMC__) && !defined(_Win32)
#include <unistd.h>
#endif
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int EPSIO_yywrap (void );
#else
extern int EPSIO_yywrap (void );
#endif
#endif

    static void EPSIO_yyEPSIO_unput (int c,char *buf_ptr  );
    
#ifndef EPSIO_yytext_ptr
static void EPSIO_yy_flex_strncpy (char *,EPSIO_yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int EPSIO_yy_flex_strlen (EPSIO_yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int EPSIO_yyEPSIO_input (void );
#else
static int EPSIO_input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( EPSIO_yytext, EPSIO_yyleng, 1, EPSIO_yyout )
#endif

/* Gets EPSIO_input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( EPSIO_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( EPSIO_yyin ) ) \
			YY_FATAL_ERROR( "EPSIO_input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, EPSIO_yyin))==0 && ferror(EPSIO_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "EPSIO_input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(EPSIO_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "EPSIO_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef EPSIO_yyterminate
#define EPSIO_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) EPSIO_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int EPSIO_yylex (void);

#define YY_DECL int EPSIO_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after EPSIO_yytext and EPSIO_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register EPSIO_yy_state_type EPSIO_yy_current_state;
	register char *EPSIO_yy_cp, *EPSIO_yy_bp;
	register int EPSIO_yy_act;
    
#line 57 "./lexer.l"


#line 666 "lex.EPSIO_yy.c"

	if ( (EPSIO_yy_init) )
		{
		(EPSIO_yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (EPSIO_yy_start) )
			(EPSIO_yy_start) = 1;	/* first start state */

		if ( ! EPSIO_yyin )
			EPSIO_yyin = stdin;

		if ( ! EPSIO_yyout )
			EPSIO_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			EPSIO_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				EPSIO_yy_create_buffer(EPSIO_yyin,YY_BUF_SIZE );
		}

		EPSIO_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		EPSIO_yy_cp = (EPSIO_yy_c_buf_p);

		/* Support of EPSIO_yytext. */
		*EPSIO_yy_cp = (EPSIO_yy_hold_char);

		/* EPSIO_yy_bp points to the position in EPSIO_yy_ch_buf of the start of
		 * the current run.
		 */
		EPSIO_yy_bp = EPSIO_yy_cp;

		EPSIO_yy_current_state = (EPSIO_yy_start);
EPSIO_yy_match:
		do
			{
			register YY_CHAR EPSIO_yy_c = EPSIO_yy_ec[YY_SC_TO_UI(*EPSIO_yy_cp)];
			if ( EPSIO_yy_accept[EPSIO_yy_current_state] )
				{
				(EPSIO_yy_last_accepting_state) = EPSIO_yy_current_state;
				(EPSIO_yy_last_accepting_cpos) = EPSIO_yy_cp;
				}
			while ( EPSIO_yy_chk[EPSIO_yy_base[EPSIO_yy_current_state] + EPSIO_yy_c] != EPSIO_yy_current_state )
				{
				EPSIO_yy_current_state = (int) EPSIO_yy_def[EPSIO_yy_current_state];
				if ( EPSIO_yy_current_state >= 34 )
					EPSIO_yy_c = EPSIO_yy_meta[(unsigned int) EPSIO_yy_c];
				}
			EPSIO_yy_current_state = EPSIO_yy_nxt[EPSIO_yy_base[EPSIO_yy_current_state] + (unsigned int) EPSIO_yy_c];
			++EPSIO_yy_cp;
			}
		while ( EPSIO_yy_base[EPSIO_yy_current_state] != 55 );

EPSIO_yy_find_action:
		EPSIO_yy_act = EPSIO_yy_accept[EPSIO_yy_current_state];
		if ( EPSIO_yy_act == 0 )
			{ /* have to back up */
			EPSIO_yy_cp = (EPSIO_yy_last_accepting_cpos);
			EPSIO_yy_current_state = (EPSIO_yy_last_accepting_state);
			EPSIO_yy_act = EPSIO_yy_accept[EPSIO_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( EPSIO_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*EPSIO_yy_cp = (EPSIO_yy_hold_char);
			EPSIO_yy_cp = (EPSIO_yy_last_accepting_cpos);
			EPSIO_yy_current_state = (EPSIO_yy_last_accepting_state);
			goto EPSIO_yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 "./lexer.l"
{EPSIO_yylval.s = strdup(EPSIO_yytext); Return(INTEGER);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "./lexer.l"
Return(EXP);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "./lexer.l"
{EPSIO_yylval.s = strdup(EPSIO_yytext); Return(WORD);}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 65 "./lexer.l"
{int len = strlen(EPSIO_yytext);
                                   EPSIO_yytext[len-1] = 0;
                                   EPSIO_yylval.s = strdup(EPSIO_yytext+1);
                                   Return(WORD);}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 70 "./lexer.l"
{EPSIO_yylval.s = strdup(EPSIO_yytext); Return(STRING);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "./lexer.l"
Return(OPEN);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 74 "./lexer.l"
Return(CLOSE);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "./lexer.l"
Return(COMMA);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "./lexer.l"
Return(OPEN_SQUARE);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "./lexer.l"
Return(CLOSE_SQUARE);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 82 "./lexer.l"
Return(EQUALS);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "./lexer.l"
Return(PERIOD);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 86 "./lexer.l"
;
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 88 "./lexer.l"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "./lexer.l"
{       loop:
#ifdef __cplusplus
                          while (EPSIO_yyEPSIO_input() != '*');
                          switch (EPSIO_yyEPSIO_input())
#else
                          while (EPSIO_input() != '*');
                          switch (EPSIO_input())
#endif
                                  {
                                  case '/': break;
                                  case '*': EPSIO_unput('*');
                                  default: goto loop;
                                  }
                          }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "./lexer.l"
Return(ERROR);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 107 "./lexer.l"
ECHO;
	YY_BREAK
#line 853 "lex.EPSIO_yy.c"
case YY_STATE_EOF(INITIAL):
	EPSIO_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int EPSIO_yy_amount_of_matched_text = (int) (EPSIO_yy_cp - (EPSIO_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*EPSIO_yy_cp = (EPSIO_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or EPSIO_input source.  It's
			 * possible that this happened because the user
			 * just pointed EPSIO_yyin at a new source and called
			 * EPSIO_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new EPSIO_input source.
			 */
			(EPSIO_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_EPSIO_input_file = EPSIO_yyin;
			YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for EPSIO_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since EPSIO_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in EPSIO_input().
		 */
		if ( (EPSIO_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[(EPSIO_yy_n_chars)] )
			{ /* This was really a NUL. */
			EPSIO_yy_state_type EPSIO_yy_next_state;

			(EPSIO_yy_c_buf_p) = (EPSIO_yytext_ptr) + EPSIO_yy_amount_of_matched_text;

			EPSIO_yy_current_state = EPSIO_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * EPSIO_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			EPSIO_yy_next_state = EPSIO_yy_try_NUL_trans( EPSIO_yy_current_state );

			EPSIO_yy_bp = (EPSIO_yytext_ptr) + YY_MORE_ADJ;

			if ( EPSIO_yy_next_state )
				{
				/* Consume the NUL. */
				EPSIO_yy_cp = ++(EPSIO_yy_c_buf_p);
				EPSIO_yy_current_state = EPSIO_yy_next_state;
				goto EPSIO_yy_match;
				}

			else
				{
				EPSIO_yy_cp = (EPSIO_yy_c_buf_p);
				goto EPSIO_yy_find_action;
				}
			}

		else switch ( EPSIO_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(EPSIO_yy_did_buffer_switch_on_eof) = 0;

				if ( EPSIO_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * EPSIO_yy_get_next_buffer() to have set up
					 * EPSIO_yytext, we can now set up
					 * EPSIO_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(EPSIO_yy_c_buf_p) = (EPSIO_yytext_ptr) + YY_MORE_ADJ;

					EPSIO_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (EPSIO_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(EPSIO_yy_c_buf_p) =
					(EPSIO_yytext_ptr) + EPSIO_yy_amount_of_matched_text;

				EPSIO_yy_current_state = EPSIO_yy_get_previous_state(  );

				EPSIO_yy_cp = (EPSIO_yy_c_buf_p);
				EPSIO_yy_bp = (EPSIO_yytext_ptr) + YY_MORE_ADJ;
				goto EPSIO_yy_match;

			case EOB_ACT_LAST_MATCH:
				(EPSIO_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[(EPSIO_yy_n_chars)];

				EPSIO_yy_current_state = EPSIO_yy_get_previous_state(  );

				EPSIO_yy_cp = (EPSIO_yy_c_buf_p);
				EPSIO_yy_bp = (EPSIO_yytext_ptr) + YY_MORE_ADJ;
				goto EPSIO_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of EPSIO_yylex */

/* EPSIO_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int EPSIO_yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf;
	register char *source = (EPSIO_yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (EPSIO_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[(EPSIO_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (EPSIO_yy_c_buf_p) - (EPSIO_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((EPSIO_yy_c_buf_p) - (EPSIO_yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_n_chars = (EPSIO_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int EPSIO_yy_c_buf_p_offset =
				(int) ((EPSIO_yy_c_buf_p) - b->EPSIO_yy_ch_buf);

			if ( b->EPSIO_yy_is_our_buffer )
				{
				int new_size = b->EPSIO_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->EPSIO_yy_buf_size += b->EPSIO_yy_buf_size / 8;
				else
					b->EPSIO_yy_buf_size *= 2;

				b->EPSIO_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					EPSIO_yyrealloc((void *) b->EPSIO_yy_ch_buf,b->EPSIO_yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->EPSIO_yy_ch_buf = 0;

			if ( ! b->EPSIO_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner EPSIO_input buffer overflow" );

			(EPSIO_yy_c_buf_p) = &b->EPSIO_yy_ch_buf[EPSIO_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[number_to_move]),
			(EPSIO_yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_n_chars = (EPSIO_yy_n_chars);
		}

	if ( (EPSIO_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			EPSIO_yyrestart(EPSIO_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(EPSIO_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[(EPSIO_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[(EPSIO_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(EPSIO_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[0];

	return ret_val;
}

/* EPSIO_yy_get_previous_state - get the state just before the EOB char was reached */

    static EPSIO_yy_state_type EPSIO_yy_get_previous_state (void)
{
	register EPSIO_yy_state_type EPSIO_yy_current_state;
	register char *EPSIO_yy_cp;
    
	EPSIO_yy_current_state = (EPSIO_yy_start);

	for ( EPSIO_yy_cp = (EPSIO_yytext_ptr) + YY_MORE_ADJ; EPSIO_yy_cp < (EPSIO_yy_c_buf_p); ++EPSIO_yy_cp )
		{
		register YY_CHAR EPSIO_yy_c = (*EPSIO_yy_cp ? EPSIO_yy_ec[YY_SC_TO_UI(*EPSIO_yy_cp)] : 1);
		if ( EPSIO_yy_accept[EPSIO_yy_current_state] )
			{
			(EPSIO_yy_last_accepting_state) = EPSIO_yy_current_state;
			(EPSIO_yy_last_accepting_cpos) = EPSIO_yy_cp;
			}
		while ( EPSIO_yy_chk[EPSIO_yy_base[EPSIO_yy_current_state] + EPSIO_yy_c] != EPSIO_yy_current_state )
			{
			EPSIO_yy_current_state = (int) EPSIO_yy_def[EPSIO_yy_current_state];
			if ( EPSIO_yy_current_state >= 34 )
				EPSIO_yy_c = EPSIO_yy_meta[(unsigned int) EPSIO_yy_c];
			}
		EPSIO_yy_current_state = EPSIO_yy_nxt[EPSIO_yy_base[EPSIO_yy_current_state] + (unsigned int) EPSIO_yy_c];
		}

	return EPSIO_yy_current_state;
}

/* EPSIO_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = EPSIO_yy_try_NUL_trans( current_state );
 */
    static EPSIO_yy_state_type EPSIO_yy_try_NUL_trans  (EPSIO_yy_state_type EPSIO_yy_current_state )
{
	register int EPSIO_yy_is_jam;
    	register char *EPSIO_yy_cp = (EPSIO_yy_c_buf_p);

	register YY_CHAR EPSIO_yy_c = 1;
	if ( EPSIO_yy_accept[EPSIO_yy_current_state] )
		{
		(EPSIO_yy_last_accepting_state) = EPSIO_yy_current_state;
		(EPSIO_yy_last_accepting_cpos) = EPSIO_yy_cp;
		}
	while ( EPSIO_yy_chk[EPSIO_yy_base[EPSIO_yy_current_state] + EPSIO_yy_c] != EPSIO_yy_current_state )
		{
		EPSIO_yy_current_state = (int) EPSIO_yy_def[EPSIO_yy_current_state];
		if ( EPSIO_yy_current_state >= 34 )
			EPSIO_yy_c = EPSIO_yy_meta[(unsigned int) EPSIO_yy_c];
		}
	EPSIO_yy_current_state = EPSIO_yy_nxt[EPSIO_yy_base[EPSIO_yy_current_state] + (unsigned int) EPSIO_yy_c];
	EPSIO_yy_is_jam = (EPSIO_yy_current_state == 33);

	return EPSIO_yy_is_jam ? 0 : EPSIO_yy_current_state;
}

    static void EPSIO_yyEPSIO_unput (int c, register char * EPSIO_yy_bp )
{
	register char *EPSIO_yy_cp;
    
    EPSIO_yy_cp = (EPSIO_yy_c_buf_p);

	/* undo effects of setting up EPSIO_yytext */
	*EPSIO_yy_cp = (EPSIO_yy_hold_char);

	if ( EPSIO_yy_cp < YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (EPSIO_yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf )
			*--dest = *--source;

		EPSIO_yy_cp += (int) (dest - source);
		EPSIO_yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_n_chars =
			(EPSIO_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buf_size;

		if ( EPSIO_yy_cp < YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--EPSIO_yy_cp = (char) c;

	(EPSIO_yytext_ptr) = EPSIO_yy_bp;
	(EPSIO_yy_hold_char) = *EPSIO_yy_cp;
	(EPSIO_yy_c_buf_p) = EPSIO_yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int EPSIO_yyEPSIO_input (void)
#else
    static int EPSIO_input  (void)
#endif

{
	int c;
    
	*(EPSIO_yy_c_buf_p) = (EPSIO_yy_hold_char);

	if ( *(EPSIO_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* EPSIO_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (EPSIO_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_ch_buf[(EPSIO_yy_n_chars)] )
			/* This was really a NUL. */
			*(EPSIO_yy_c_buf_p) = '\0';

		else
			{ /* need more EPSIO_input */
			int offset = (EPSIO_yy_c_buf_p) - (EPSIO_yytext_ptr);
			++(EPSIO_yy_c_buf_p);

			switch ( EPSIO_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because EPSIO_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for EPSIO_input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					EPSIO_yyrestart(EPSIO_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( EPSIO_yywrap( ) )
						return EOF;

					if ( ! (EPSIO_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return EPSIO_yyEPSIO_input();
#else
					return EPSIO_input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(EPSIO_yy_c_buf_p) = (EPSIO_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (EPSIO_yy_c_buf_p);	/* cast for 8-bit char's */
	*(EPSIO_yy_c_buf_p) = '\0';	/* preserve EPSIO_yytext */
	(EPSIO_yy_hold_char) = *++(EPSIO_yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different EPSIO_input stream.
 * @param EPSIO_input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void EPSIO_yyrestart  (FILE * EPSIO_input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        EPSIO_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            EPSIO_yy_create_buffer(EPSIO_yyin,YY_BUF_SIZE );
	}

	EPSIO_yy_init_buffer(YY_CURRENT_BUFFER,EPSIO_input_file );
	EPSIO_yy_load_buffer_state( );
}

/** Switch to a different EPSIO_input buffer.
 * @param new_buffer The new EPSIO_input buffer.
 * 
 */
    void EPSIO_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		EPSIO_yypop_buffer_state();
	 *		EPSIO_yypush_buffer_state(new_buffer);
     */
	EPSIO_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(EPSIO_yy_c_buf_p) = (EPSIO_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buf_pos = (EPSIO_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_n_chars = (EPSIO_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	EPSIO_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (EPSIO_yywrap()) processing, but the only time this flag
	 * is looked at is after EPSIO_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(EPSIO_yy_did_buffer_switch_on_eof) = 1;
}

static void EPSIO_yy_load_buffer_state  (void)
{
    	(EPSIO_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_n_chars;
	(EPSIO_yytext_ptr) = (EPSIO_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buf_pos;
	EPSIO_yyin = YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_EPSIO_input_file;
	(EPSIO_yy_hold_char) = *(EPSIO_yy_c_buf_p);
}

/** Allocate and initialize an EPSIO_input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE EPSIO_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) EPSIO_yyalloc(sizeof( struct EPSIO_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in EPSIO_yy_create_buffer()" );

	b->EPSIO_yy_buf_size = size;

	/* EPSIO_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->EPSIO_yy_ch_buf = (char *) EPSIO_yyalloc(b->EPSIO_yy_buf_size + 2  );
	if ( ! b->EPSIO_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in EPSIO_yy_create_buffer()" );

	b->EPSIO_yy_is_our_buffer = 1;

	EPSIO_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with EPSIO_yy_create_buffer()
 * 
 */
    void EPSIO_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->EPSIO_yy_is_our_buffer )
		EPSIO_yyfree((void *) b->EPSIO_yy_ch_buf  );

	EPSIO_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a EPSIO_yyrestart() or at EOF.
 */
    static void EPSIO_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	EPSIO_yy_flush_buffer(b );

	b->EPSIO_yy_EPSIO_input_file = file;
	b->EPSIO_yy_fill_buffer = 1;

    /* If b is the current buffer, then EPSIO_yy_init_buffer was _probably_
     * called from EPSIO_yyrestart() or through EPSIO_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->EPSIO_yy_bs_lineno = 1;
        b->EPSIO_yy_bs_column = 0;
    }

        b->EPSIO_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void EPSIO_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->EPSIO_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->EPSIO_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->EPSIO_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->EPSIO_yy_buf_pos = &b->EPSIO_yy_ch_buf[0];

	b->EPSIO_yy_at_bol = 1;
	b->EPSIO_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		EPSIO_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void EPSIO_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	EPSIO_yyensure_buffer_stack();

	/* This block is copied from EPSIO_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(EPSIO_yy_c_buf_p) = (EPSIO_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_buf_pos = (EPSIO_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->EPSIO_yy_n_chars = (EPSIO_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(EPSIO_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from EPSIO_yy_switch_to_buffer. */
	EPSIO_yy_load_buffer_state( );
	(EPSIO_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void EPSIO_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	EPSIO_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((EPSIO_yy_buffer_stack_top) > 0)
		--(EPSIO_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		EPSIO_yy_load_buffer_state( );
		(EPSIO_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void EPSIO_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(EPSIO_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(EPSIO_yy_buffer_stack) = (struct EPSIO_yy_buffer_state**)EPSIO_yyalloc
								(num_to_alloc * sizeof(struct EPSIO_yy_buffer_state*)
								);
		
		memset((EPSIO_yy_buffer_stack), 0, num_to_alloc * sizeof(struct EPSIO_yy_buffer_state*));
				
		(EPSIO_yy_buffer_stack_max) = num_to_alloc;
		(EPSIO_yy_buffer_stack_top) = 0;
		return;
	}

	if ((EPSIO_yy_buffer_stack_top) >= ((EPSIO_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (EPSIO_yy_buffer_stack_max) + grow_size;
		(EPSIO_yy_buffer_stack) = (struct EPSIO_yy_buffer_state**)EPSIO_yyrealloc
								((EPSIO_yy_buffer_stack),
								num_to_alloc * sizeof(struct EPSIO_yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((EPSIO_yy_buffer_stack) + (EPSIO_yy_buffer_stack_max), 0, grow_size * sizeof(struct EPSIO_yy_buffer_state*));
		(EPSIO_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the EPSIO_input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE EPSIO_yy_scan_buffer  (char * base, EPSIO_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) EPSIO_yyalloc(sizeof( struct EPSIO_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in EPSIO_yy_scan_buffer()" );

	b->EPSIO_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->EPSIO_yy_buf_pos = b->EPSIO_yy_ch_buf = base;
	b->EPSIO_yy_is_our_buffer = 0;
	b->EPSIO_yy_EPSIO_input_file = 0;
	b->EPSIO_yy_n_chars = b->EPSIO_yy_buf_size;
	b->EPSIO_yy_is_interactive = 0;
	b->EPSIO_yy_at_bol = 1;
	b->EPSIO_yy_fill_buffer = 0;
	b->EPSIO_yy_buffer_status = YY_BUFFER_NEW;

	EPSIO_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the EPSIO_input buffer state to scan a string. The next call to EPSIO_yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       EPSIO_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE EPSIO_yy_scan_string (EPSIO_yyconst char * EPSIO_yy_str )
{
    
	return EPSIO_yy_scan_bytes(EPSIO_yy_str,strlen(EPSIO_yy_str) );
}

/** Setup the EPSIO_input buffer state to scan the given bytes. The next call to EPSIO_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE EPSIO_yy_scan_bytes  (EPSIO_yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	EPSIO_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) EPSIO_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in EPSIO_yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = EPSIO_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in EPSIO_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->EPSIO_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void EPSIO_yy_fatal_error (EPSIO_yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine EPSIO_yyless() so it works in section 3 code. */

#undef EPSIO_yyless
#define EPSIO_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up EPSIO_yytext. */ \
        int EPSIO_yyless_macro_arg = (n); \
        YY_LESS_LINENO(EPSIO_yyless_macro_arg);\
		EPSIO_yytext[EPSIO_yyleng] = (EPSIO_yy_hold_char); \
		(EPSIO_yy_c_buf_p) = EPSIO_yytext + EPSIO_yyless_macro_arg; \
		(EPSIO_yy_hold_char) = *(EPSIO_yy_c_buf_p); \
		*(EPSIO_yy_c_buf_p) = '\0'; \
		EPSIO_yyleng = EPSIO_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int EPSIO_yyget_lineno  (void)
{
        
    return EPSIO_yylineno;
}

/** Get the EPSIO_input stream.
 * 
 */
FILE *EPSIO_yyget_in  (void)
{
        return EPSIO_yyin;
}

/** Get the output stream.
 * 
 */
FILE *EPSIO_yyget_out  (void)
{
        return EPSIO_yyout;
}

/** Get the length of the current token.
 * 
 */
int EPSIO_yyget_leng  (void)
{
        return EPSIO_yyleng;
}

/** Get the current token.
 * 
 */

char *EPSIO_yyget_text  (void)
{
        return EPSIO_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void EPSIO_yyset_lineno (int  line_number )
{
    
    EPSIO_yylineno = line_number;
}

/** Set the EPSIO_input stream. This does not discard the current
 * EPSIO_input buffer.
 * @param in_str A readable stream.
 * 
 * @see EPSIO_yy_switch_to_buffer
 */
void EPSIO_yyset_in (FILE *  in_str )
{
        EPSIO_yyin = in_str ;
}

void EPSIO_yyset_out (FILE *  out_str )
{
        EPSIO_yyout = out_str ;
}

int EPSIO_yyget_debug  (void)
{
        return EPSIO_yy_flex_debug;
}

void EPSIO_yyset_debug (int  bdebug )
{
        EPSIO_yy_flex_debug = bdebug ;
}

/* EPSIO_yylex_destroy is for both reentrant and non-reentrant scanners. */
int EPSIO_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		EPSIO_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		EPSIO_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	EPSIO_yyfree((EPSIO_yy_buffer_stack) );
	(EPSIO_yy_buffer_stack) = NULL;

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef EPSIO_yytext_ptr
static void EPSIO_yy_flex_strncpy (char* s1, EPSIO_yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int EPSIO_yy_flex_strlen (EPSIO_yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *EPSIO_yyalloc (EPSIO_yy_size_t  size )
{
	return (void *) malloc( size );
}

void *EPSIO_yyrealloc  (void * ptr, EPSIO_yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void EPSIO_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see EPSIO_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "EPSIO_yytables"

#undef YY_NEW_FILE
#undef YY_FLUSH_BUFFER
#undef EPSIO_yy_set_bol
#undef EPSIO_yy_new_buffer
#undef EPSIO_yy_set_interactive
#undef EPSIO_yytext_ptr
#undef YY_DO_BEFORE_ACTION

#ifdef YY_DECL_IS_OURS
#undef YY_DECL_IS_OURS
#undef YY_DECL
#endif
#line 107 "./lexer.l"




# undef EPSIO_input
# define EPSIO_input() my_EPSIO_input()
#ifdef FLEX_SCANNER
static int lex_EPSIO_input() {
  return EPSIO_input();
}
#else	/* BSD/AT&T lex */
#ifndef EPSIO_input
# error "Sorry, but need either flex or AT&T lex"
#endif
static int lex_EPSIO_input() {
  return EPSIO_input();
}

static int my_EPSIO_unput(char c)
{
  if (lex_read_from_string != 0) {
    /* Make sure we have something */
    if (lex_string_ptr) {
      if (c == '\n') EPSIO_yylineno--;
      lex_string_ptr--;
    }
  } else {
    EPSIO_yytchar= (c);if(EPSIO_yytchar=='\n')EPSIO_yylineno--;*EPSIO_yysptr++=EPSIO_yytchar;
/*    EPSIO_unput(c); Causes infinite recursion! */
  }
  return c;
}

#endif

/* Public */
void LIOFromFile(FILE *fd)
{
  lex_read_from_string = 0;
  EPSIO_yyin = fd;
  /* Don't know why this is necessary, but otherwise
   * lex only works _once_!
   */
#ifdef FLEX_SCANNER
  EPSIO_yyrestart(fd);
  EPSIO_yy_init = 1;
#endif
}

void LIOFromString(char *buffer)
{
  lex_read_from_string = 1;
  lex_buffer = buffer;
  lex_buffer_length = strlen(buffer);
  lex_string_ptr = 0;
  /* Don't know why this is necessary, but otherwise
   * lex only works _once_!
   */
#ifdef FLEX_SCANNER
  EPSIO_yy_init = 1;
#endif
}

static int my_EPSIO_input( void )
{
  if (lex_read_from_string) {
    if (lex_string_ptr == lex_buffer_length)
      return 0;
    else {
      char c = lex_buffer[lex_string_ptr++];
#ifndef FLEX_SCANNER
      if (c == '\n') EPSIO_yylineno++;
#endif
      return c;
    }
  } else {
    return lex_EPSIO_input();
  }
}

int wxExioCleanUp()
{
#ifdef FLEX_SCANNER
	/* flex <= 2.5.9 */
	if (YY_CURRENT_BUFFER)
		EPSIO_yy_delete_buffer(YY_CURRENT_BUFFER);
#endif
	return 0;
}

